config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :contacts
 #root 'contacts#index'
 get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, :email, :phone, presence: true
    validates :phone, presence: true, length: { is: 10 }
    validates_uniqueness_of :name, :email, :phone
    has_one_attached :image
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    # validates email
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
      # finds user with session data and stores it if present
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    def require_user_logged_in!
      # allows only logged in user
      redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :find_contact, only: [:edit, :update, :destroy]
    def index
      @contacts = Contact.paginate(page: params[:page], per_page: 5)
    end
    def new
     @contact = Contact.new
    end
    def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "Successfully created new contact"
      redirect_to contacts_path
    else
      render 'new'
    end
    end
    def edit
    end
    def update
      if @contact.update(contact_params)
        flash[:success] = "Successfully Update contact"
        redirect_to contacts_path
      else
        render 'edit'
      end
    end
    def destroy
      if @contact.destroy
        flash[:success] = "Successfully Deleted contact"
        redirect_to contacts_path
      end
    end
    def find_contact
      @contact = Contact.find(params[:id])
    end
    private
    def contact_params
      params.require(:contact).permit(:name, :email, :company, :address ,:phone ,:dob, :image)
    end
  end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    # allows only logged in users
    before_action :require_user_logged_in!
    def edit; end
    def update
      # update user password
      if Current.user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    # instantiates new user
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
      # stores saved user id in a session
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Successfully created account'
      else
        render :new
      end
    end
    private
    def user_params
      # strong parameters
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new; end
    def create
      user = User.find_by(email: params[:email])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to contacts_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
    <div class="panel-body">
      <% if @contact.errors.any? %>
        <div class="row">
          <div class="col-md-12">
            <div class="alert alert-danger">
              <h3>Please correct this following errors:</h3>
              <ul>
                <% @contact.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      <div class="form-horizontal">
        <div class="row">
          <div class="col-md-8">
            <div class="form-group">
              <%= f.label :name, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
<div class="form-group">
          
            </div>
            <div class="form-group">
              <%= f.label :company, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :company, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :email, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :phone, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :phone, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :address, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_area :address, class: "form-control" %>
              </div>
            </div>
      <div class="form-group">
              <label for="group" class="control-label col-md-3">Group</label>
              <div class="col-md-5">
                <select name="group" id="group" class="form-control">
                  <option value="">Select group</option>
                  <option value="1">Family</option>
                  <option value="2">Friend</option>
                  <option value="3">Other</option>
                </select>
              </div>
              <div class="col-md-3">
                <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
              </div>
            </div>
            <div class="form-group" id="add-new-group" style="display: none;">
              <div class="col-md-offset-3 col-md-8">
                <div class="input-group">
                  <input type="text" name="new_group" id="new_group" class="form-control">
                  <span class="input-group-btn">
                    <a href="#" class="btn btn-default">
                      <i class="glyphicon glyphicon-ok"></i>
                    </a>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :image, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.file_field :image, class: "form-control" %>
              </div>
          </div>
          <div class="col-md-4">
            <div class="fileinput fileinput-new" data-provides="fileinput">
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <button type="submit" class="btn btn-primary">Save</button>
              <%= link_to "Cancel", contacts_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/contacts/edit.html.erb
<div class="card">
              <div class="panel-heading">
                <strong>Edit Contact</strong>
              </div>
           <%= render 'form' %>
        </div>

app/views/contacts/index.html.erb
<div class="panel panel-default">
    <table class="table">
    <% @contacts.each do |contact| %>
      <tr>
        <td class="middle">
          <div class="media">
            <div class="media-left">
              <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                 <% if contact.image.attached? %>
                      <%= link_to image_tag(contact.image, style:"height:100%"), contacts_path%>
                 <% else %>
                    <img class="image" src="https://cdn-icons-png.flaticon.com/512/149/149071.png">
                 <% end %>
              </div>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= contact.name %></h4>
              <address>
                <strong><%= contact.company %></strong><br>
                <%= contact.email %>
              </address>
            </div>
          </div>
        </td>
        <td width="100" class="middle">
          <div>
            <%= link_to edit_contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: "Edit" do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
            <%= link_to contact_path(contact), :method => :delete, class: "btn btn-circle btn-danger btn-xs", title: "Delete", data: { confirm: "Are you sure ?" } do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
  <div class="text-center">
<%= will_paginate %>
</div>

app/views/contacts/new.html.erb
<div class="card">
              <div class="card-header">
                <strong>Add Contact</strong>
              </div>
              <%= render 'form' %>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02"> </div>
        <a class="navbar-brand text-uppercase" href="/contacts">
           MY CONTACTS
        </a>
        <% if Current.user %>
           <div class="container-fluid pull-right"><%= button_to 'Logout', logout_path, method: :delete %></div>
           <div class="container-fluid pull-right"><a href="/contacts/new" class="btn btn-danger">Add New</a></div>
        <% else %>
        <b>
        <div class="container-fluid pull-right"><%= button_to 'Login', sign_in_path %>
        <%= link_to "<button>Signup</button>".html_safe, sign_up_path, :class=>"inbox-sf-add-btn tip" %><div>
        </b>
        <% end %>
        </div>
    </nav>
    <!-- content -->
    <main class="pt-5">
      <div class="container">
        <div class="row">
          <div class="col-md-9">
          <% flash.each do |type, message| %>
            <%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= message %>
            <% end %>
          <% end %>
               <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/password/edit.html.erb
<h1>Edit Password</h1>
  <%= form_with model: Current.user, url: edit_password_path do |f| %>
    <p>
    <%= f.label 'password:'%><br>
    <%= f.password_field :password %>
    </p>
    <p>
    <%= f.label 'password_confirmation:'%><br>
    <%= f.password_field :password_confirmation %>
    </p>
    <p>
    <%= f.submit 'Update' %>
    </p>
  <% end %>

app/views/welcome/index.html.erb
<html>
<body>
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
      </div>
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
        <form>
         <% if Current.user %>
    Logged in as: <b><%= Current.user.email %></b><br>
    <%= link_to "<button>Edit Password</button>".html_safe, edit_password_path, :class=>"inbox-sf-add-btn tip" %>
        <% end %>
  <div id="grad1"></div>
        </form>
      </div>
    </div>
  </div>
</section>
</body>
</html>